# Generated by Django 3.2.16 on 2022-12-18 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('birth_date', models.DateField()),
                ('graduation_date', models.DateField()),
                ('grade', models.FloatField()),
                ('degree', models.CharField(choices=[('BA', 'Bachelor'), ('MA', 'Master'), ('PHD', 'Doctorate')], max_length=3)),
                ('identifier', models.CharField(max_length=10, unique=True)),
            ],
        ),
    ]
